const $=id=>document.getElementById(id);let state=null,selectedChain=null,lastReview=null;
async function api(route,payload){const response=await fetch('/api/trake/'+route,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw new Error(data.error||'Request failed');return data}
function message(text,error=false){$('message').textContent=text;$('message').className=error?'warnings':''}
function eventCard(event){return `<div class="event"><div class="event-head"><span class="marker">${event.order}</span><button data-delete="${event.event_id}">×</button></div><div class="event-row"><button data-up="${event.event_id}">↑</button><input data-text="${event.event_id}" value="${event.text.replaceAll('"','&quot;')}"><select data-required="${event.event_id}"><option value="true" ${event.required?'selected':''}>required</option><option value="false" ${!event.required?'selected':''}>optional</option></select></div><label>Modalities<input data-modalities="${event.event_id}" value="${event.modalities.join(',')}"></label><small>${event.source}</small></div>`}
function wireEditor(){document.querySelectorAll('[data-up]').forEach(b=>b.onclick=()=>{const i=state.request.events.findIndex(e=>e.event_id===b.dataset.up);if(i>0)[state.request.events[i-1],state.request.events[i]]=[state.request.events[i],state.request.events[i-1]];renumber();render({state})});document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{if(state.request.events.length>1){state.request.events=state.request.events.filter(e=>e.event_id!==b.dataset.delete);renumber();render({state})}})}
function renumber(){state.request.events.forEach((event,index)=>{event.order=index+1;event.event_id='e'+(index+1)})}
function keyframeImage(candidate,label){if(!candidate||!candidate.keyframe_path)return `<div class="thumb missing">No image</div>`;const url=`/keyframe?path=${encodeURIComponent(candidate.keyframe_path)}`;return `<img class="thumb" src="${url}" alt="${label}" loading="lazy" onerror="this.replaceWith(Object.assign(document.createElement('div'),{className:'thumb missing',textContent:'Image unavailable'}))">`}
function videoCard(video){const previews=(state.pools||[]).map(pool=>({event:pool.event,candidate:pool.candidates.find(item=>item.video_id===video.video_id)})).filter(item=>item.candidate);return `<div class="video"><b>${video.video_id}</b><p>${video.required_coverage}/${video.required_total} required · ${video.complete?'complete':'incomplete'}</p><div class="preview-row">${previews.map(item=>`<figure>${keyframeImage(item.candidate,`${video.video_id} ${item.event.event_id}`)}<figcaption>${item.event.event_id}<br>F${item.candidate.keyframe_id} · ${item.candidate.pts_time.toFixed(1)}s</figcaption></figure>`).join('')||'<small>Chưa có keyframe candidate.</small>'}</div><p class="warnings">${video.warnings.join(', ')}</p></div>`}
function render(data){state=data.state;$('events').innerHTML=state.request.events.map(eventCard).join('');wireEditor();$('search').disabled=false;$('save-plan').disabled=false;$('add-event').disabled=state.request.events.length>=5;$('videos').innerHTML=(state.videos||[]).map(videoCard).join('')||'<p>Chưa retrieve.</p>';$('chains').innerHTML=(state.alignments||[]).flatMap(a=>a.chains.map(c=>chainCard(c))).join('')||'<p>Chưa có chain. Bấm “Align timeline” để ghép các ảnh theo thời gian.</p>';document.querySelectorAll('[data-chain]').forEach(button=>button.onclick=()=>selectChain(button.dataset.chain));}
function chainCard(chain){const selected=chain.events.filter(e=>e.candidate);const max=Math.max(1,...selected.map(e=>e.candidate.pts_time));return `<div class="chain"><div class="chain-head"><b>${chain.video_id}</b><span class="score">${chain.score.final_score.toFixed(3)}</span></div><div class="timeline">${selected.map(e=>`<i style="left:${Math.min(98,e.candidate.pts_time/max*98)}%" title="${e.event_id} @ ${e.candidate.pts_time}s"></i>`).join('')}</div><div class="chain-events">${selected.map(e=>`<figure>${keyframeImage(e.candidate,`${chain.video_id} ${e.event_id}`)}<figcaption><b>${e.event_id}</b><br>frame ${e.candidate.keyframe_id}<br>${e.candidate.pts_time.toFixed(2)}s</figcaption></figure>`).join('')}</div><p class="warnings">${chain.warnings.join(', ')}</p><button data-chain="${chain.chain_id}">Select chain</button></div>`}
function selectChain(id){selectedChain=(state.alignments||[]).flatMap(a=>a.chains).find(c=>c.chain_id===id);$('selection').textContent=selectedChain?`${selectedChain.chain_id} · ${selectedChain.video_id}`:'Chưa chọn';$('confirm').disabled=!selectedChain;$('reject').disabled=!selectedChain;const pools=Object.fromEntries((state.pools||[]).map(p=>[p.event.event_id,p.candidates.filter(c=>c.video_id===selectedChain.video_id)]));$('corrections').innerHTML=selectedChain.events.map(e=>`<label>${e.event_id}<select data-replace="${e.event_id}">${(pools[e.event_id]||[]).map(c=>`<option value="${c.candidate_id}" ${e.candidate&&c.candidate_id===e.candidate.candidate_id?'selected':''}>frame ${c.keyframe_id} @ ${c.pts_time.toFixed(2)}s</option>`).join('')}</select><button data-apply="${e.event_id}">Replace + lock</button><button data-refine="${e.event_id}">Refine</button></label>`).join('');document.querySelectorAll('[data-apply]').forEach(b=>b.onclick=()=>replaceEvent(b.dataset.apply));document.querySelectorAll('[data-refine]').forEach(b=>b.onclick=()=>refineEvent(b.dataset.refine));}
$('plan').onclick=async()=>{try{const data=await api('plan',{query:$('query').value});render(data);$('align').disabled=true;message('Đã tạo plan revision 1. Review events trước khi retrieve.')}catch(e){message(e.message,true)}};
$('add-event').onclick=()=>{if(state.request.events.length<5){const order=state.request.events.length+1;state.request.events.push({event_id:'e'+order,order,text:'new event',clip_query:'new event',modalities:['clip'],required:true,object_constraints:[],attribute_constraints:[],ocr_constraints:[],asr_constraints:[],min_gap_seconds:null,max_gap_seconds:null,confidence:1,source:'manual'});render({state})}};
$('save-plan').onclick=async()=>{try{state.request.events.forEach(event=>{event.text=document.querySelector(`[data-text="${event.event_id}"]`).value;event.clip_query=event.text;event.required=document.querySelector(`[data-required="${event.event_id}"]`).value==='true';event.modalities=document.querySelector(`[data-modalities="${event.event_id}"]`).value.split(',').map(x=>x.trim()).filter(Boolean);event.source='manual'});const data=await api('update-plan',{session_id:state.session_id,events:state.request.events,constraints:state.request.constraints});render(data);$('align').disabled=true;message(`Đã lưu plan revision ${state.plan_revision}; cần retrieve lại.`)}catch(e){message(e.message,true)}};
$('search').onclick=async()=>{try{const data=await api('search',{session_id:state.session_id});render(data);$('align').disabled=false;message('Đã retrieve candidate theo từng event.')}catch(e){message(e.message,true)}};
$('align').onclick=async()=>{try{const data=await api('align',{session_id:state.session_id});render(data);message('Đã align cùng video theo pts_time.')}catch(e){message(e.message,true)}};
async function review(decision){try{const data=await api('review',{session_id:state.session_id,chain_id:selectedChain.chain_id,decision,reviewer:$('reviewer').value});lastReview=data.review;$('export').disabled=decision!=='confirmed';message(`Review ${decision} đã được append.`)}catch(e){message(e.message,true)}}
$('confirm').onclick=()=>review('confirmed');$('reject').onclick=()=>review('rejected');$('export').onclick=async()=>{try{await api('export',{session_id:state.session_id,review_id:lastReview.review_id});message('Đã tạo internal record; đây không phải format nộp BTC.')}catch(e){message(e.message,true)}};
async function replaceEvent(eventId){try{const candidateId=document.querySelector(`[data-replace="${eventId}"]`).value;const data=await api('replace',{session_id:state.session_id,chain_id:selectedChain.chain_id,event_id:eventId,candidate_id:candidateId,lock_event:true});render(data);selectedChain=data.state.manual_chain;message(`${eventId} đã được thay và khóa; invariant đã kiểm tra lại.`)}catch(e){message(e.message,true)}}
async function refineEvent(eventId){try{const data=await api('refine',{session_id:state.session_id,chain_id:selectedChain.chain_id,event_id:eventId});message(`${data.refinement.status}: ${data.refinement.reason}`)}catch(e){message(e.message,true)}}
